.TH _PRINTF 1 "17 March 2020" "version 1.0"
.DT _printf 1
.SH NAME
_printf \- prints and format data
.Sh SYNOPSIS
_printf
.Op FORMAT
.Op Fl ARGUMENT
...
.SH DESCRIPTION
Print ARGUMENT(s) according to FORMAT
.PP
FORMAT controls the output. Interpreted sequences are:

.PP
%c prints a character
.PP
%s prints a string
.PP
%% prints a single %
.PP
%i prints an integer
.PP
%d prints an integer
.PP
%u prints an unsigned data
.PP
%o prints an unsigned octal
.PP
%x prints an unsigned hexadecimal in lower case
.PP
%X prints an unsigned hexadecimal in upper case
.PP
%p prints a memory address
.PP
%r prints a reverse string
.El
.Pp

.SH EXAMPLES
.PP
 _printf("Length:[%d, %i]\n", len, len);
.PP
 _printf("Character:[%c]\n", 'H');

.SH SEE ALSO
printf(1)

.SH REPORTING BUGS
Report printf bugs to 1514@holbertonschool.com or
1620@holbertonschool.com

.SH AUTHORS
Written by Cristian Castiblanco and John Garcia.

.SH COPYRIGHT
Copyright © 2020 Holberton School. This is free software: you are free to change and redistribute it.
